### ISSUE TITLE
Text-davinci-003 is broken

### ISSUE THREAD

**Issue by mak448a** [mak448a/AI-Drawing-ChatBot#48]
**Describe the bug**
Text davinci 003 is broken as described by #45 

**To Reproduce**
Just configure text davinci as your model

**Comment by mak448a** [comment]
Solution: Probably just find another chinese mirror

**Comment by mak448a** [comment]
Should we just delete text-davinci-003 from the repo? @mishalhossin

**Comment by mishalhossin** [comment]
> Should we just delete text-davinci-003 from the repo? I think ChatGPT is good enough @mishalhossin

i guess

**Comment by mak448a** [comment]
Done!
