### ISSUE TITLE
Slash commands don't work by default

### ISSUE THREAD

**Issue by guguxh** [mak448a/AI-Drawing-ChatBot#49]
**Describe the bug**
I can start the bot normally but I can't use the slash commands. Also, when I don't use the activate.bat like in steps, I can't run the bot cause I get an error about importing imaginepy.

**To Reproduce**
Follow all the instructions in the README file

**Screenshots**
![image](https://github.com/mak448a/AI-Drawing-ChatBot/assets/61206153/56cfb1aa-9f2b-4dc9-949b-4358bf3cefad)
![image](https://github.com/mak448a/AI-Drawing-ChatBot/assets/61206153/becff449-6edb-4dda-a704-762a5474b9b2)
![image](https://github.com/mak448a/AI-Drawing-ChatBot/assets/61206153/1bd649d9-b208-4a8d-9fcf-f3e23fecbe82)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10
 - Python Version: 3.10.9

**Additional context**
I followed the steps correctly.

**Comment by guguxh** [comment]
Also, Imaginepy is down.

**Comment by mak448a** [comment]
Really?

**Comment by mak448a** [comment]
Hold on, lemme check things out

**Comment by mak448a** [comment]
> **Describe the bug** I can start the bot normally but I can't use the slash commands. Also, when I don't use the activate.bat like in steps, I can't run the bot cause I get an error about importing imaginepy.
> 
> **To Reproduce** Idk
> 
> **Screenshots** ![image](https://user-images.githubusercontent.com/61206153/247649682-56cfb1aa-9f2b-4dc9-949b-4358bf3cefad.png) ![image](https://user-images.githubusercontent.com/61206153/247650495-becff449-6edb-4dda-a704-762a5474b9b2.png) ![image](https://user-images.githubusercontent.com/61206153/247650652-1bd649d9-b208-4a8d-9fcf-f3e23fecbe82.png)
> 
> **Desktop (please complete the following information):**
> 
>     * OS: Windows
> 
>     * Version: 10
> 
>     * Python Version: 3.10.9
> 
> 
> **Additional context** I followed the steps correctly.

Sorry, I didn't write it on the main README. You have to uncomment `await bot.tree.sync()` in the code. I'll remove this step later

**Comment by mak448a** [comment]
> Also, Imaginepy is down.

It seems like it, I can't generate any picture from them

**Comment by mak448a** [comment]
Please delete the whole folder and try again now that the code has been updated 😀

**Comment by guguxh** [comment]
![image](https://github.com/mak448a/AI-Drawing-ChatBot/assets/61206153/70d9209e-4b45-4ffe-8d23-3ce9a9c6547a)
Also, I can't download gpt4all :(

**Comment by mak448a** [comment]
> ![image](https://user-images.githubusercontent.com/61206153/247769082-70d9209e-4b45-4ffe-8d23-3ce9a9c6547a.png) Also, I can't download gpt4all :(

I don't know why that would be the case

**Comment by mak448a** [comment]
Any updates on the slash commands? Does it work now with the new code?

**Comment by guguxh** [comment]
> Any updates on the slash commands? Does it work now with the new code?

For sure, works fine, just the thing about Imaginepy doesnt work :) 

I have a question and this I think doesnt need a issue to:
![image](https://github.com/mak448a/AI-Drawing-ChatBot/assets/61206153/06f86626-be24-4f87-8b22-e033d924b332)
thats normal?

**Comment by mak448a** [comment]
Yeah, that's totally normal.

**Comment by mak448a** [comment]
I should've hid those though

**Comment by guguxh** [comment]
> I should've hid those though

Nah, I think if you put a timer in the message where indicate the time needed to complete, will be cool, just if you want :)

**Comment by mak448a** [comment]
Honestly that code wasn't written by me :)

**Comment by mak448a** [comment]
Closing as the problem was fixed
