### ISSUE TITLE
Chatbot drawing model selection in config

### ISSUE THREAD

**Issue by mak448a** [mak448a/AI-Drawing-ChatBot#58]

**Comment by mishalhossin** [comment]
**ssdahsdashkldjahsldhasldjashdjkasdkajsdkjasdglasjdasjldgalsdjfasdljfagsdjfsfjkasdklfjahldfkjasdhlkfjasdhlfajksdhlfkajsdhflaksjdfhalsdkfjhasldkfjahsdkljfahsdfkljahsdklfjahrhalehsldhfauiefhaiweuhadlufiahsdfui**

**Comment by mak448a** [comment]
@mishalhossin Are you okay? You seem bored/depressed

**Comment by mak448a** [comment]
Let's do this!
