### ISSUE TITLE
Use InquirerPy for getting credentials

### ISSUE THREAD

**Issue by mak448a** [mak448a/AI-Drawing-ChatBot#61]
Just use [InquirerPy](https://inquirerpy.readthedocs.io/en/latest/) instead of the current bash `read` command that we're using in the setup script

**Comment by mishalhossin** [comment]
So it makes it look cool ?

**Comment by mak448a** [comment]
Yes

**Comment by mak448a** [comment]
Might as well do this now

**Comment by mak448a** [comment]
You know, this seems like extra bloat. Tell me if you still want it though

**Comment by mak448a** [comment]
https://github.com/mak448a/AI-Drawing-ChatBot/blob/main/run.py

**Comment by mishalhossin** [comment]
> https://github.com/mak448a/AI-Drawing-ChatBot/blob/main/run.py This is how it's going currently

that will probly not work on replit

**Comment by mak448a** [comment]
Maybe I should disable it for replit but just use it for local

**Comment by mishalhossin** [comment]
> Maybe I should disable it for replit but just use it for local

you can write to .env files and it will create it as secret tho.

**Comment by mishalhossin** [comment]
and you can detect enviorment variable by loading them and checking if its not None

**Comment by mak448a** [comment]
Done!
