### ISSUE TITLE
Add Prodia

### ISSUE THREAD

**Issue by mishalhossin** [mak448a/AI-Drawing-ChatBot#69]
https://prodia.com/
https://docs.prodia.com/reference/getting-started

**Comment by mak448a** [comment]
This actually looks like it might be worth to add :) However, I have other projects I want to work on

**Comment by mishalhossin** [comment]
> This actually looks like it might be worth to add :) However, I have other projects I want to work on

i got shit loads of api keys if you want

**Comment by mishalhossin** [comment]
Keys :- https://pastebin.mozilla.org/roQALE5w/raw

**Comment by mak448a** [comment]
What the… Did you make a script to make these? Anyway, thank you!

**Comment by mak448a** [comment]
I can't find out how to download. I found out, however, that I can use https://api.prodia.com/job/{JOB_ID} to see if the image was finished. Supposedly, you can also [download from here](https://github.com/zenafey/prodiapy/blob/main/prodia/async_prodia.py#L130C29-L130C75), but I couldn't get that to work.

**Comment by mak448a** [comment]
Closing since I added SDXL 1.0 from stable horde. Also, I couldn't find out how to get the api to work. Comment if you still want this feature

**Comment by mak448a** [comment]
https://docs.prodia.com/reference/getjob

**Comment by mak448a** [comment]
I added it!

**Comment by mishalhossin** [comment]
Nice
