### ISSUE TITLE
Create 'Cogs' for Commands and Organize Helper Functions

### ISSUE THREAD

**Issue by mishalhossin** [mak448a/AI-Drawing-ChatBot#70]
**Issue Description:**

**Problem:**
Our project currently lacks a modular structure for managing commands and helper functions. This makes it challenging to maintain, scale, and collaborate effectively.

**Proposed Solution:**
We should implement a 'cogs' system for organizing commands and create a separate folder for helper functions to improve project structure and maintainability.

**Details:**

**1. Implement 'Cogs' for Commands:**
   - **Description:** Discord.py offers a 'cogs' system that allows us to organize commands into separate modules. This promotes modularity and makes it easier to manage different parts of the bot.
   - **Steps to Implement:**
     - Create a 'cogs' directory to store command modules.
     - Refactor existing commands into separate cog classes within this directory.
     - Register these cogs in the bot's main file.

**2. Organize Helper Functions:**
   - **Description:** Helper functions are essential for various tasks. Organizing them in a dedicated folder will make it easier to find and reuse them across the project.
   - **Steps to Implement:**
     - Create a 'utils' or 'helpers' directory to store helper functions.
     - Move existing helper functions into this directory.
     - Update imports to reflect the new folder structure.

**Expected Benefits:**
- Improved code organization and maintainability.
- Easier collaboration with team members.
- Simplified debugging and testing.

**Comment by mishalhossin** [comment]
Feel free to ask for assistance 😃

**Comment by mak448a** [comment]
> Feel free to ask for assistance 😃

Yeah I've never used cogs before but I have seen them before

**Comment by mishalhossin** [comment]
### cogs/PingCog.py
```
from discord.ext import commands


class PingCog(commands.Cog):
    def __init__(self, bot):
        self.bot = bot

    @commands.hybrid_command(name="ping", description="PONG")
    async def ping(self, ctx):
        latency = self.bot.latency * 1000
        await ctx.send(f"Ping: {latency:.2f} ms")


async def setup(bot):
    await bot.add_cog(PingCog(bot))

```
### You can use setup hook to load cogs
```
class CogBOT(commands.Bot):
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)

    async def setup_hook(self) -> None:
        await self.load_extension("cogs.PingCog")


bot = CogBOT(command_prefix="/", intents=discord.Intents.all(), help_command=None)
```

### Example of a cog using event listeners
```
from discord.ext import commands


class OnError(commands.Cog):
    def __init__(self, bot):
        self.bot = bot

    @commands.Cog.listener()
    async def on_command_error(self, ctx, error):
            await ctx.send(f"``{error}```", ephemeral=True)


async def setup(bot):
    await bot.add_cog(OnError(bot))

```

**Comment by mishalhossin** [comment]
There are more examples on the docs
https://discordpy.readthedocs.io/en/stable/ext/commands/cogs.html

**Comment by mak448a** [comment]
Done in 2c3a02cec5f80659537204352f94879f70683494
