### ISSUE TITLE
Add gpt4free / Chatbot is broken

### ISSUE THREAD

**Issue by mak448a** [mak448a/AI-Drawing-ChatBot#72]
The chatbot is broken. It throws an error whenever you open it.

Fix will probably have to be completely replacing vercel-llm-api. This is why I don't like reverse-engineered apis. When they work, they're awesome, but otherwise.... 🤦🏽‍♂️

**Comment by mak448a** [comment]
I'm also starting to lose motivation for this project....

**Comment by mishalhossin** [comment]
> I'm also starting to lose motivation for this project....

But you learned a lot of stuff along the way

**Comment by mishalhossin** [comment]
Look into https://makersuite.google.com/app/home it has free ai models for text and chat completion

**Comment by mak448a** [comment]
> > I'm also starting to lose motivation for this project....
> 
> But you learned a lot of stuff along the way

Yeah, I did. Thank you for your help.

> Look into https://makersuite.google.com/app/home it has free ai models for text and chat completion

That looks like it might work 👍

**Comment by mak448a** [comment]
Going to add gpt4free
