### ISSUE TITLE
Remove your poe token from git history

### ISSUE THREAD

**Issue by mishalhossin** [mak448a/AI-Drawing-ChatBot#74]
...

**Comment by mak448a** [comment]
Did I leak it?

**Comment by mak448a** [comment]
Could you post the commit/file link?

**Comment by mishalhossin** [comment]
> Could you post the commit/file link?

https://github.com/mak448a/AI-Drawing-ChatBot/commit/1fbb2ac
https://github.com/mak448a/AI-Drawing-ChatBot/commit/ad9abcf

**Comment by mak448a** [comment]
Ok, thanks. I'll just change my password.

**Comment by mak448a** [comment]
Lol I realized that this was an example key (notice that the pattern is very QWERTY-like) 😅

**Comment by mishalhossin** [comment]
> Lol I realized that this was an example key (notice that the pattern is very QWERTY-like) 😅

lol
